Repository codeamp/panel, pull requests merged in 2018-12, with the labels that each got.

#298 Secrets drawer traps mouse
  src/components/Admin/Secrets/index.js
Labels: T/Bug

#292 Fix 'project create' error report
  src/components/App/index.js
  src/components/App/style.module.css
  src/components/Create/index.js
  src/lib/apollo.js
  src/mobx/stores/app-store.js
Labels: P/Low, S/Review, T/Bug

#291 Fix Keyboard Search Selection
  src/components/TopNav/index.js
  src/components/TopNav/style.module.css
Labels: P/Low, S/Review, T/Bug

#300 Fix Error when Navigating Via SearchBar
  src/components/Admin/Secrets/index.js
  src/components/Project/EnvironmentSelector/index.js
  src/components/TopNav/index.js
Labels: P/High, T/Bug

#304 Fix issue when visiting a project page with a direct link
  src/components/Project/Extensions/index.js
  src/components/Project/Features/index.js
  src/components/Project/Releases/index.js
  src/components/Project/Secrets/index.js
  src/components/Project/Secrets/paginator.js
  src/components/Project/Services/index.js
  src/components/Project/Settings/index.js
  src/components/Project/index.js
Labels: P/High, S/Review, T/Bug

#306 Websocket Handlers Fixes
  src/components/Project/Extensions/index.js
  src/components/Project/Features/index.js
  src/components/Project/Releases/index.js
Labels: P/Medium, S/Review, T/Bug

#305 Lazy load secret values when clicked
  package-lock.json
  src/components/Project/Secrets/paginator.js
Labels: S/Ready, T/Enhancement

#308 Evaluate first position idx values correctly for secrets loading
  src/components/Project/Secrets/paginator.js
Labels: S/Review

#310 Speed Up Project View
  src/components/Project/index.js
Labels: P/Medium, S/Review

#311 Change font to use Trebuchet MS for Dashboard
  src/components/Dashboard/style.module.css
Labels: P/Low

#313 Release Touchups
  src/components/Project/Features/index.js
  src/components/Project/Releases/index.js
Labels: P/Low, T/Bug
