Repository codeamp/panel, pull requests merged in 2018-07, with the labels that each got.

#180 Refactor graphql queries to reflect *List type for Pagination
  src/components/Admin/Extensions/index.js
  src/components/Admin/Projects/index.js
  src/components/Admin/Secrets/index.js
  src/components/App/index.js
  src/components/Dashboard/index.js
  src/components/Project/Extensions/LoadBalancer/index.js
  src/components/Project/Extensions/Route53/index.js
  src/components/Project/Extensions/index.js
  src/components/Project/Features/index.js
  src/components/Project/Releases/index.js
  src/components/Project/Secrets/index.js
  src/components/Project/Services/index.js
  src/components/Project/index.js
  src/components/TopNav/index.js
Labels: P/High, S/Review

#199 Toggling/Selecting the same environment while on the Secrets tab causes render to fail
  src/components/Project/index.js
Labels: P/High, S/Review, T/Bug

#192 Remove environmentID as a required param in CreateProject
  src/components/Create/index.js
Labels: P/Medium, S/Review, T/Bug

#193 Add PanelTable component w/ Pagination and apply to Secrets table
  package-lock.json
  package.json
  src/components/Project/Secrets/index.js
  src/components/Project/index.js
  src/components/Utils/Pagination/index.js
  src/components/Utils/Pagination/style.module.css
  src/components/Utils/Table/index.js
  src/components/Utils/Table/style.module.css
  src/mobx/stores/app-store.js
Labels: P/High, S/Review, T/Enhancement

#202 Service deploy strategy
  package-lock.json
  src/components/Project/Services/index.js
  src/components/Project/Services/style.module.css
Labels: S/Review

#203 Don't close drawer when there's an error on creation
  src/components/Project/Secrets/index.js
  src/components/Utils/Pagination/index.js
  src/components/Utils/Table/index.js
Labels: S/Review, T/Bug

#205 fix: Show "Continuous Deploy" when CD deploys the release
  src/components/Project/Releases/index.js
  src/components/Project/Releases/style.module.css
Labels: P/Medium, S/Review, T/Bug

#201 Fixes issues with Admin/Projects
  src/components/Admin/Projects/index.js
Labels: P/Medium, S/Review

#209 Fix: Services Dialog Presents 'Confirm Changes' Dialog
  src/components/Project/Services/index.js
Labels: P/Medium, S/Review, S/Tested, T/Bug

#211 Fix: 404 Page on Project Create
  src/components/Project/index.js
Labels: P/Medium, S/Review, S/Tested, T/Bug

#212 Fix Stop Release Button
  src/components/Project/Releases/index.js
Labels: P/Low, S/Review, T/Bug

#213 Improve timestamps display / reduce clutter
  package-lock.json
  package.json
  src/components/Admin/Environments/index.js
  src/components/Admin/Secrets/index.js
  src/components/Admin/Users/index.js
  src/components/Project/Features/index.js
  src/components/Project/Releases/index.js
  src/components/Project/Secrets/index.js
  src/components/Project/Services/index.js
Labels: P/Low, S/Review, S/Tested

#210 init form for health probe headers
  src/components/Project/Services/index.js
  src/components/Project/Services/style.module.css
Labels: S/Review

#215 Environment History Timestamp
  src/components/Utils/EnvVarVersionHistory/index.js
Labels: T/Enhancement

#217 Display Canceled Releases
  src/components/Admin/Projects/index.js
  src/components/Project/Releases/index.js
Labels: S/Review

#219 Fix for Admin Extensions Confirmation Dialog
  src/components/Admin/Extensions/index.js
Labels: S/Review, T/Bug

#220 Fix: getLatestSuccessfulRelease returns nulls everytime
  src/components/Project/Releases/index.js
Labels: P/High, T/Bug

#223 Modify getLatestSuccessfulRelease to skip currentRelease
  src/components/Project/Releases/index.js
Labels: P/High, T/Bug

#221 fix: always route to releases page when feature is clicked for deploy
  src/components/Project/Features/index.js
  src/components/Project/index.js
Labels: P/Medium, S/Review, T/Bug

#222 Force rebuilds on Feature deploys
  src/components/Project/Features/index.js
Labels: P/High, S/Review, T/Bug
