Repository codeamp/panel, pull requests merged in 2018-09, with the labels that each got.

#252 Update Material UI + Glyphing + Extension Env Selection
  package-lock.json
  package.json
  src/components/Admin/Environments/index.js
  src/components/Admin/Extensions/index.js
  src/components/Admin/Extensions/style.module.css
  src/components/Admin/Secrets/index.js
  src/components/Admin/ServiceSpecs/index.js
  src/components/Dashboard/index.js
  src/components/Form/envvar-select-field.js
  src/components/LeftNav/index.js
  src/components/Project/Extensions/LoadBalancer/index.js
  src/components/Project/Extensions/index.js
  src/components/Project/Features/index.js
  src/components/Project/Releases/index.js
  src/components/Project/Secrets/paginator.js
  src/components/Project/Services/index.js
  src/components/Project/index.js
  src/components/Utils/EnvVarVersionHistory/index.js
  src/components/Utils/Tooltip/index.js
Labels: P/Low, S/Review, T/Enhancement

#254 Route53 Labels
  src/components/Project/Extensions/Route53/index.js
Labels: P/Low, T/Enhancement

#257 Update React and Apollo Packages.
  package-lock.json
  package.json
  src/components/Project/Releases/index.js
  src/lib/apollo.js
Labels: P/Medium, S/Review, T/Enhancement

#258 Services Pagination
  .gitignore
  src/components/Project/Releases/index.js
  src/components/Project/Services/index.js
  src/components/Utils/Pagination/index.js
  src/components/Utils/Paginator/index.js
Labels: P/Medium, S/Review, T/Enhancement

#256 Release Badges
  src/components/Project/Releases/index.js
  src/components/Project/Releases/style.module.css
Labels: P/Low, S/Review

#255 Fix Sidebar Badges
  src/components/LeftNav/index.js
  src/components/Project/index.js
Labels: P/Low, S/Review, T/Enhancement

#263 Releases Arrow
  src/components/Project/Releases/index.js
Labels: P/Low, T/Enhancement

#261 Add max character limit for service names
  src/components/Project/Services/index.js
Labels: P/Low, S/Review

#264 Cleans up erronous '>' that appears in admin extension page
  src/components/Admin/Extensions/index.js
Labels: P/Low, S/Review, T/Bug
