Repository codeamp/panel, pull requests merged in 2018-08, with the labels that each got.

#226 Add button to sync git commits
  src/components/Project/Features/index.js
Labels: P/Low, S/Review

#228 Show a timer for how long a release takes to complete
  src/components/Project/Releases/index.js
  src/components/Project/Releases/style.module.css
Labels: P/High, S/In Progress, T/Feature Request

#232 Fix eslint
  src/components/Project/Releases/index.js
Labels: P/High, S/Review

#231 Bookmarked Projects on Dashboard
  src/components/App/index.js
  src/components/Dashboard/index.js
  src/components/Dashboard/style.module.css
  src/components/Project/Environment/index.js
Labels: S/Review

#235 Dashboard Updates + Search Bar
  src/components/Dashboard/index.js
  src/components/Dashboard/style.module.css
  src/components/Project/Environment/index.js
  src/components/Project/Environment/style.module.css
  src/components/TopNav/index.js
Labels: S/Review, T/Bug, T/Enhancement

#242 Hide Cancel Release Button
  src/components/Project/Releases/index.js
Labels: P/Medium, S/Review

#246 Pagination Touchups + Glyphing
  src/components/Admin/Projects/index.js
  src/components/Admin/Secrets/index.js
  src/components/App/index.js
  src/components/Dashboard/index.js
  src/components/Project/Secrets/index.js
  src/components/Project/Secrets/paginator.js
  src/components/Project/Services/index.js
  src/components/Project/index.js
  src/components/TopNav/index.js
  src/components/Utils/Pagination/index.js
  src/components/Utils/Table/index.js
  src/mobx/stores/app-store.js
Labels: S/Review

#248 Fixes for issues arising from pagination-touchups branch
  src/components/App/index.js
  src/components/Project/Secrets/paginator.js
  src/components/TopNav/index.js
  src/components/Utils/EnvVarVersionHistory/index.js
Labels: S/Review

#247 Fix Secrets (+) Button
  src/components/Project/Secrets/paginator.js
Labels: S/Review, T/Bug
