Repository codeamp/panel, pull requests merged in 2018-11, with the labels that each got.

#274 Add cacheable property to extensions and fix Extension layout
  src/components/Admin/Extensions/index.js
  src/components/Admin/Extensions/style.module.css
Labels: P/High, S/Review

#282 Fix NPM Module Issues
  package.json
Labels: S/Review, T/Bug

#281 Disable Autocomplete for Route53 Field
  src/components/Form/input-field.js
  src/components/Project/Extensions/Route53/index.js
Labels: P/Medium, T/Bug

#285 Added 404 message for projects not found
  src/components/Project/Environment/index.js
Labels: P/Medium, S/Review, T/Bug

#286 Project/Environments Routing Fixes
  src/components/App/index.js
  src/components/Dashboard/index.js
  src/components/LeftNav/index.js
  src/components/LeftNav/style.module.css
  src/components/Project/Environment/index.js
  src/components/Project/index.js
  src/components/Projects/index.js
Labels: P/Medium, S/Review, T/Bug

#288 Project Routing Bugfixes
  src/components/App/index.js
  src/components/Project/Environment/index.js
  src/components/Project/EnvironmentSelector/index.js
  src/components/Project/EnvironmentSelector/style.module.css
  src/components/Project/index.js
Labels: P/High, S/Review, T/Bug

#290 Bugfix: Project Environment Selector
  src/components/Project/index.js
Labels: P/High, S/Review, T/Bug

#287 Disable service spec selection when creating service
  src/components/Admin/ServiceSpecs/index.js
  src/components/Project/Services/index.js
Labels: S/Review
